name: 自动编译和压缩  # 工作流程名称

on: 
  workflow_dispatch:  # 只能手动触发工作流程
  # [push, pull_request] push时触发 
jobs:
  automate:
    runs-on: windows-latest  # 运行环境为最新Windows

    steps:
      - name: 拉取代码  # 获取仓库代码
        uses: actions/checkout@v2
  
      - name: 设置Python环境  # 配置Python环境
        uses: actions/setup-python@v2
        with:
           python-version: 3.8  # 使用Python 3.8

      - name: 安装Nuitka  # 安装Nuitka
        run: python -m pip install nuitka

      - name: 安装UPX  # 安装UPX
        run: |
          choco install upx

      - name: 编译并压缩  # 使用Nuitka进行编译并用UPX进行压缩
        run: |  
          cd nuitka编译upx压缩  # 切换工作目录到你的.py文件和.ico文件所在位置
          python -m nuitka --follow-imports --windows-icon-from-ico=note.ico sesame-to-ruby.py  # 使用Nuitka进行编译
          upx --best sesame-to-ruby.exe  # 使用UPX进行压缩

      - name: 上传构建产物
        uses: actions/upload-artifact@v2
        with:
          name: compiled-exe  # 产物的名称
          path: ./nuitka编译upx压缩/sesame-to-ruby.exe  # 产物的路径

      - name: 自动标签并推送
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          default_bump: patch

      - name: 创建发布
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: 发布版 ${{ steps.tag_version.outputs.new_tag }}
          asset_path: ./nuitka编译upx压缩/sesame-to-ruby.exe
          asset_name: sesame-to-ruby.exe
          asset_content_type: application/octet-stream
